### ISSUE TITLE
About how to use geojson-jackson to parse geojson

### ISSUE THREAD

**Issue by dianadujing** [opendatalab-de/geojson-jackson#20]
Hi there,

When I tried to use this lib to parse geojson data with the following code:
```
GeoJsonObject object = mapper.readValue(geometryJson, GeoJsonObject.class);
if (object instanceof Polygon) {
	Polygon  polygon = (Polygon) object; 
} else if (object instanceof LineString) {
	LineString lineString = (LineString) object;
}
```
I got this error:
```
[err] org.codehaus.jackson.map.JsonMappingException: Can not construct instance of org.codehaus.jackson.map.type.SimpleType, problem: abstract types can only be instantiated with additional type information
 at [Source: java.io.StringReader@13ed8e85; line: 1, column: 1]
[err] 	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:160)
[err] 	at org.codehaus.jackson.map.deser.StdDeserializationContext.instantiationException(StdDeserializationContext.java:214)
[err] 	at org.codehaus.jackson.map.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:44)
[err] 	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:1980)
[err] 	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1271)
```
Could you please show me the right way to use it?

**Comment by dianadujing** [comment]
I think I have solved it. When I used this lib, "org.codehaus.jackson.*" was imported, not "fasterxml". That leads to this error.
